Class msg.checkReservationExistParPlaqueDmde Extends (Ens.Request, %JSON.Adaptor)
{

Property plaque As %String;

Storage Default
{
<Data name="checkReservationExistParPlaqueDmdeDefaultData">
<Subscript>"checkReservationExistParPlaqueDmde"</Subscript>
<Value name="1">
<Value>plaque</Value>
</Value>
</Data>
<DefaultData>checkReservationExistParPlaqueDmdeDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
